// Code generated by MockGen. DO NOT EDIT.
// Source: service/service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/paramonies/avito-rest-advert/internal/app/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateAdvert mocks base method.
func (m *MockService) CreateAdvert(arg0 model.Advert) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdvert", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdvert indicates an expected call of CreateAdvert.
func (mr *MockServiceMockRecorder) CreateAdvert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdvert", reflect.TypeOf((*MockService)(nil).CreateAdvert), arg0)
}

// GetAdvertById mocks base method.
func (m *MockService) GetAdvertById(arg0 int, arg1 []string) (model.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertById", arg0, arg1)
	ret0, _ := ret[0].(model.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertById indicates an expected call of GetAdvertById.
func (mr *MockServiceMockRecorder) GetAdvertById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertById", reflect.TypeOf((*MockService)(nil).GetAdvertById), arg0, arg1)
}

// GetAdvertList mocks base method.
func (m *MockService) GetAdvertList(arg0 int, arg1 string) ([]model.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertList", arg0, arg1)
	ret0, _ := ret[0].([]model.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertList indicates an expected call of GetAdvertList.
func (mr *MockServiceMockRecorder) GetAdvertList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertList", reflect.TypeOf((*MockService)(nil).GetAdvertList), arg0, arg1)
}
